// WARNING: DO NOT EDIT. This file is Auto-Generated by AWS Mobile Hub. It will be overwritten.

// Copyright 2017-2018 Amazon.com, Inc. or its affiliates (Amazon). All Rights Reserved.
// Code generated by AWS Mobile Hub. Amazon gives unlimited permission to
// copy, distribute and modify it.

// AWS Mobile Hub Project Constants
const awsmobile = {
    'aws_app_analytics': 'enable',
    'aws_cloud_logic': 'enable',
    'aws_cloud_logic_custom': [{"id":"liwagfv5uj","name":"sampleCloudApi","description":"","endpoint":"https://liwagfv5uj.execute-api.us-east-1.amazonaws.com/Development","region":"us-east-1","paths":["/items","/items/123"]},{"id":"aeq0kvjizl","name":"TheCostTableCRUD","description":"","endpoint":"https://aeq0kvjizl.execute-api.us-east-1.amazonaws.com/Development","region":"us-east-1","paths":["/TheCostTable","/TheCostTable/123"]}],
    'aws_cognito_identity_pool_id': 'us-east-1:2a6beba0-d8d4-4ba6-a29c-86c6f65ea969',
    'aws_cognito_region': 'us-east-1',
    'aws_content_delivery': 'enable',
    'aws_content_delivery_bucket': 'thebudgetcalculatora-hosting-mobilehub-398931277',
    'aws_content_delivery_bucket_region': 'us-east-1',
    'aws_content_delivery_cloudfront': 'enable',
    'aws_content_delivery_cloudfront_domain': 'd4fwiygbg5k6q.cloudfront.net',
    'aws_dynamodb': 'enable',
    'aws_dynamodb_all_tables_region': 'us-east-1',
    'aws_dynamodb_table_schemas': [{"tableName":"thebudgetcalculatora-mobilehub-398931277-TheCostTable","attributes":[{"name":"ID","type":"S"},{"name":"ItemName","type":"S"},{"name":"Price","type":"N"}],"indexes":[],"region":"us-east-1","hashKey":"ID"}],
    'aws_mobile_analytics_app_id': '46080173f10f44f7a5ce069395e425f6',
    'aws_mobile_analytics_app_region': 'us-east-1',
    'aws_project_id': '1b526593-46e3-4b1e-9e83-1a72cb7c755b',
    'aws_project_name': 'the-budget-calculator-app-project',
    'aws_project_region': 'us-east-1',
    'aws_resource_bucket_name': 'thebudgetcalculatora-deployments-mobilehub-398931277',
    'aws_resource_name_prefix': 'thebudgetcalculatora-mobilehub-398931277',
}

export default awsmobile;
